[package]
name = "usagi-thirawat"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
csv.workspace = true
serde.workspace = true
serde_json.workspace = true
usagi-common = { path = "../usagi-common" }
usagi-contracts = { path = "../usagi-contracts" }

[dev-dependencies]
tempfile.workspace = true
